import type { Metadata } from "next";

import { AdminLayout } from "@/components/layout/admin-layout";
import { QueryProvider } from "@/lib/react-query";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <AdminLayout>{children}</AdminLayout>
        </QueryProvider>
      </body>
    </html>
  );
}
