export const CHART_TYPE_MAP = {
  BD_SH_W: {
    id: "BD_SH_W",
    part: "몸통",
    property: "어깨",
    type: "너비",
    label: "어깨 너비",
  },
  BD_AH_W: {
    id: "BD_AH_W",
    part: "몸통",
    property: "진동",
    type: "너비",
    label: "진동 너비",
  },
  BD_CH_W: {
    id: "BD_CH_W",
    part: "몸통",
    property: "가슴",
    type: "너비",
    label: "가슴 너비",
  },
  BD_WST_W: {
    id: "BD_WST_W",
    part: "몸통",
    property: "허리",
    type: "너비",
    label: "허리 너비",
  },
  BD_UAH_W: {
    id: "BD_UAH_W",
    part: "몸통",
    property: "진동하단",
    type: "너비",
    label: "진동하단 너비",
  },
  BD_NK_C: {
    id: "BD_NK_C",
    part: "몸통",
    property: "목",
    type: "둘레",
    label: "목 둘레",
  },
  BD_CH_C: {
    id: "BD_CH_C",
    part: "몸통",
    property: "가슴",
    type: "둘레",
    label: "가슴 둘레",
  },
  SL_SCP_L: {
    id: "SL_SCP_L",
    part: "소매",
    property: "소매산",
    type: "길이",
    label: "소매산 길이",
  },
  BD_ALL_L: {
    id: "BD_ALL_L",
    part: "몸통",
    property: "전체",
    type: "길이",
    label: "총장",
  },
  SL_ALL_W: {
    id: "SL_ALL_W",
    part: "소매",
    property: "전체",
    type: "너비",
    label: "소매너비",
  },
  BD_SHL_L: {
    id: "BD_SHL_L",
    part: "몸통",
    property: "어깨경사",
    type: "길이",
    label: "어깨경사 길이",
  },
  BD_FNK_L: {
    id: "BD_FNK_L",
    part: "몸통",
    property: "앞목",
    type: "길이",
    label: "앞목 길이",
  },
  BD_BNK_L: {
    id: "BD_BNK_L",
    part: "몸통",
    property: "뒷목",
    type: "길이",
    label: "뒷목 길이",
  },
  BD_AH_L: {
    id: "BD_AH_L",
    part: "몸통",
    property: "진동",
    type: "길이",
    label: "진동 길이",
  },
  BD_FAH_L: {
    id: "BD_FAH_L",
    part: "몸통",
    property: "앞진동",
    type: "길이",
    label: "앞진동 길이",
  },
  BD_BAH_L: {
    id: "BD_BAH_L",
    part: "몸통",
    property: "뒤진동",
    type: "길이",
    label: "뒤진동 길이",
  },
  BD_WST_L: {
    id: "BD_WST_L",
    part: "몸통",
    property: "허리",
    type: "길이",
    label: "허리 길이",
  },
  BD_RG_L: {
    id: "BD_RG_L",
    part: "몸통",
    property: "래글런",
    type: "길이",
    label: "래글런 길이",
  },
  BD_BN_L: {
    id: "BD_BN_L",
    part: "몸통",
    property: "고무단",
    type: "길이",
    label: "고무단 길이",
  },
  BD_SHL_W: {
    id: "BD_SHL_W",
    part: "몸통",
    property: "어깨경사",
    type: "너비",
    label: "어깨사선 너비",
  },
  BD_FNK_W: {
    id: "BD_FNK_W",
    part: "몸통",
    property: "앞목",
    type: "너비",
    label: "앞목 너비",
  },
  BD_BNK_W: {
    id: "BD_BNK_W",
    part: "몸통",
    property: "뒷목",
    type: "너비",
    label: "뒷목 너비",
  },
  BD_BN_W: {
    id: "BD_BN_W",
    part: "몸통",
    property: "고무단",
    type: "너비",
    label: "고무단 너비",
  },
  BD_FNK_C: {
    id: "BD_FNK_C",
    part: "몸통",
    property: "앞목",
    type: "둘레",
    label: "앞목 둘레",
  },
  BD_BNK_C: {
    id: "BD_BNK_C",
    part: "몸통",
    property: "뒷목",
    type: "둘레",
    label: "뒷목 둘레",
  },
  BD_NB_L: {
    id: "BD_NB_L",
    part: "몸통",
    property: "넥밴드",
    type: "길이",
    label: "넥밴드 길이",
  },
  SL_FAH_L: {
    id: "SL_FAH_L",
    part: "소매",
    property: "앞진동",
    type: "길이",
    label: "소매 앞진동 길이",
  },
  SL_BAH_L: {
    id: "SL_BAH_L",
    part: "소매",
    property: "뒤진동",
    type: "길이",
    label: "소매 뒤진동 길이",
  },
  SL_RG_L: {
    id: "SL_RG_L",
    part: "소매",
    property: "래글런",
    type: "길이",
    label: "소매 래글런 길이",
  },
  SL_BN_L: {
    id: "SL_BN_L",
    part: "소매",
    property: "고무단",
    type: "길이",
    label: "소매 고무단 길이",
  },
  SL_SCP_W: {
    id: "SL_SCP_W",
    part: "소매",
    property: "소매산",
    type: "너비",
    label: "소매산 너비",
  },
  SL_BN_W: {
    id: "SL_BN_W",
    part: "소매",
    property: "고무단",
    type: "너비",
    label: "소매 고무단 너비",
  },
  SL_SH_C: {
    id: "SL_SH_C",
    part: "소매",
    property: "어깨",
    type: "둘레",
    label: "소매 어깨 둘레",
  },
  SL_ALL_L: {
    id: "SL_ALL_L",
    part: "소매",
    property: "전체",
    type: "길이",
    label: "소매길이",
  },
};
